version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t prathibha07/sparse_recommender_docker:latest .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push prathibha07/sparse_recommender_docker:latest

  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
      - build:
          filters:
            branches:
              only: master
